### PR TITLE
Moving (back) to marshalled session cookies

### PR DESCRIPTION
**Pull request by reidmix**
Currently with `:json` saved session cookies, the session data is transformed to json for saving which stringifies the keys of nested hashes.  Moving (back) to `:marshal` session cookies does not perform this transofrmation (I think it uses Ruby's marshalling methods which keeps the data's types). 

NOTE: Any test/development environments that have been logged into, you will need to clear your cookies (specifically the `_retrodot_session` cookie as they're not backwards compatible.

This came out of the Omniauth (#20) implementation.

### CODE REVIEW

**Comment by lexelby** [comment]
Thanks again for figuring this out.  Google totally failed me.

**Comment by lexelby** [comment]
:+1:

**Comment by joshuatobin** [comment]
Whoa nice find. 👍

**Comment by reidmix** [comment]
Yeah, it was totally a "find the right google incantation" to get to the answer.

**Pull request merged**
