### PR TITLE
Log update type

### PR DESCRIPTION
**Pull request by joshuatobin**
CC: @jmervine @reidmix @lexelby

### CODE REVIEW

**Comment by reidmix** [comment]
My thought: make sure there's no auth/tokens/etc. -- i don't think there is, but there could be in the future maybe?  There is this: https://github.com/heroku/rollbar-blanket

**Comment by joshuatobin** [comment]
@reidmix yeah good point. I'm just gonna go back to my original plan. Please look again

**Comment by lexelby** [comment]
:+1:

**Comment by jmervine** [comment]
👍

**Pull request merged**
