### PR TITLE
changing datetime display to be bold

### PR DESCRIPTION
**Pull request by jmervine**
@joshuatobin @reidmix personal preference. 
screen shot 2016-12-07 at 11 36 22 am

### CODE REVIEW

**Comment by joshuatobin** [comment]
👍

**Comment by reidmix** [comment]
Oh i like the bolding -- much easier to read and not conflicting with command words 👍

**Comment by lexelby** [comment]
@jmervine @reidmix 

I chose monospace for the dates in `/ic log` to make sure that the timestamps all take up the same width.  Switching to bold (with the default, variable-space font) means that the colons won't line up nicely.

**Comment by joshuatobin** [comment]
This also came up in user testing.

**Comment by lexelby** [comment]
@joshuatobin What specifically came up?  That people linked bold better, or that people wanted the timestamps to all be the same width?

**Comment by jmervine** [comment]
People didn't like the syntax highlighted date. No one mentioned width at all.

**Pull request merged**
