### PR TITLE
Return a list of responders when adding/removing from timeline

### PR DESCRIPTION
**Pull request by joshuatobin**
CC: @jmervine @reidmix

### CODE REVIEW

**Comment by jmervine** [comment]
👍

**Comment by lexelby** [comment]
Was this something that came out of user testing?  I didn't return the full list of responders originally to avoid cluttering the channel, but I could see how that would be confusing or not useful to users.

**Comment by jmervine** [comment]
Not sure if this came out of user testing or not. Personally, I was more in favor of this when responders were all on one line, but not that they're expanded, it might be a little much. Perhaps return a single line list of responders in this case and leave the expanded list for `/i responders`?

**Comment by joshuatobin** [comment]
This came out of user testing as well.

**Comment by lexelby** [comment]
Gotcha, so people wanted to see the list returned after they add or remove.  Perhaps it makes sense to send the list as it is now, using the "only you can see this" method, or just on one line like @jmervine suggests.

**Pull request merged**
