### PR TITLE
fix slash command errors

### LINKED ISSUE #227: Error when using /i help
retrodot-error

When using `/i help`, I get both the help text and an error message- see attachment.

### PR DESCRIPTION
**Pull request by lexelby**
Typo, should fix #227.  I also removed the original command string from retrodot's response, since it's redundant and apparently unnecessary.  Slack doesn't complain about the empty message field.

### CODE REVIEW

**Comment by joshuatobin** [comment]
@lexelby Looks good but there is a failing spec

**Comment by lexelby** [comment]
wtf how did I miss that?

**Comment by lexelby** [comment]
@tobin Fixed.  Apparently I wrote the test to match the incorrect code.  Ephemeral responses shouldn't do the delayed job / POST thing because we don't bother echoing their command to them.  I fixed the specs to expect a direct HTTP response.

**Comment by joshuatobin** [comment]
👍

**Pull request merged**
